# Generated by Django 4.0 on 2022-02-16 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_db', '0002_rename_book_id_bookcopy_book_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='date_of_checkin',
        ),
        migrations.AddField(
            model_name='history',
            name='date_of_checkin',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
