# Generated by Django 4.0 on 2022-02-17 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_db', '0003_remove_checkout_date_of_checkin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='date_of_checkout',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='history',
            name='date_of_checkin',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
